name: Build docker image for nativefier

on:
  [workflow_dispatch]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dockerfile build 
        uses: VaultVulp/gp-docker-action@1.6.0
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: nativefier
          image-tag: latest
      
      - name: Docker login 
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image for Docker Hub
        run: docker tag ghcr.io/ghostx31/website-nativefier/nativefier:latest ${{ secrets.DOCKER_USERNAME }}/nativefier:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nativefier:latest