name: Build docker image for Nativefier-downloader

on:
  push:
    tags:
      - '*'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dockerfile build 
        uses: VaultVulp/gp-docker-action@1.2.0
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: nativefier-downloader
          extract-git-tag: true
